export const ORGANIZATION_REPOSITORY = 'ORGANIZATION_REPOSITORY';
export const CARD_REPOSITORY = 'CARD_REPOSITORY';
export const TRANSACTION_REPOSITORY = 'TRANSACTION_REPOSITORY';
export const UNIT_OF_WORK = 'UNIT_OF_WORK';
